name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: curl
      uses: wei/curl@master
      with:
        args: ${{ secrets.CURL_MOTION_DRIVER }}
    - name: unzip
      uses: DuckSoft/extract-7z-action@v1.0
       with:
        pathSource: motion_driver_6.12.zip
        pathTarget: .
