name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Decompress
      uses: TonyBogdanov/zip@1.0
      with:
        args: unzip -P ${{ secrets.ZIP_PASSWORD }} -qq ./components/mpu/motion_driver_6.12.zip -d ./components/mpu/
    - name: esp-idf build
      uses: sebastianPsm/esp-idf-ci-action@1